version: "3.8"

services:
     app_proxy:
          environment:
               - APP_HOST=nalyx-umbrel-jellyseerr
               - APP_PORT=5055
     server:
          image: fallenbagel/jellyseerr:latest
          container_name: jellyseerr
          environment:
               - LOG_LEVEL=debug
          volumes:
               - ${APP_DATA_DIR}/data/config:/app/config
          restart: unless-stopped