version: "3.8"

services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
       ports:
            - 5055:5055
       volumes:
            - ${APP_DATA_DIR}/data/config:/app/config
       restart: unless-stopped