version: "3.8"

services:
     app_proxy:
          environment:
               - APP_HOST=nalyx-umbrel-jellyseerr_server_1
               - APP_PORT=3000
     server:
          image: fallenbagel/jellyseerr:latest
          environment:
               - LOG_LEVEL=debug
               - TZ=Etc/UTC
          volumes:
               - ${APP_DATA_DIR}/data/config:/app/config
          restart: unless-stopped